---
title: "Question 3"
output: html_notebook
---
```{r}
library(tidyverse)
library(kableExtra)
```

## 請作表列出107至110年各年出生男、女嬰數


```{r}
##load the data
birth = read_csv("./data/births_107_110_county_edu_age.csv")

```
```{r}
summary(birth)
```
```{r}
View(birth)
```
```{r}
names(birth)
```
```{r}
### remove 1st row ( duplicated variable names in Chinese)
birth <- birth %>%
  slice(2:929881)
```


```{r}
## change birth_count from character to numeric; statistic_yyy to factoral
birth <- birth %>% 
  mutate(birth_count=as.numeric(birth_count)) %>% 
  mutate(statistic_yyy = factor(statistic_yyy,levels=c('107','108','109','110')))
```

```{r}

## check the types of the variables
summary(birth)
```


```{r}
birth %>% 
  group_by(statistic_yyy, birth_sex) %>% 
  summarize(births = sum(birth_count)) %>% 
  pivot_wider(names_from= birth_sex,values_from = births) %>%   #### move birth_sex to column
  kbl() %>%      ### beautify
  kable_classic_2(full_width = F)
```

## 請依最多到最少排序非本國籍生母不同教育程度出生嬰兒數

```{r}
### check mother nationality
birth %>% 
  distinct(mother_nation)
```

"非本國籍"生母不同教育程度出生嬰兒數

```{r}
birth %>% 
  filter(!mother_nation=="本國") %>%   ### exclude "本國"
  group_by(mother_education) %>% 
  summarise(births=sum(birth_count)) %>% 
  arrange(desc(births)) %>% 
  rename("生母教育程度"=mother_education,"出生嬰兒數"=births) %>% 
  kable() %>% 
  kable_classic(full_width = F)
```
"本國籍"生母不同教育程度出生嬰兒數

```{r}
birth %>% 
  filter(mother_nation=="本國") %>%   ### must include "本國"
  group_by(mother_education) %>% 
  summarise(births=sum(birth_count)) %>% 
  arrange(desc(births)) %>% 
  rename("生母教育程度"=mother_education,"出生嬰兒數"=births) %>% 
  kable() %>% 
  kable_classic(full_width = F)
```
## 請依生母教育程度，畫出107年至110年各年出生嬰兒數

```{r}
birth_year_edu <- birth %>% 
  group_by(mother_education,statistic_yyy) %>% 
  summarize(births=sum(birth_count))
birth_year_edu
```


```{r}
ggplot(birth_year_edu, aes(x=statistic_yyy,y=births)) +
  geom_col() +
  facet_wrap(~mother_education,ncol=3, scales = "free_y") +
  #coord_cartesian()+
  #theme(axis.text.x = element_text(angle = 90)) +
  labs(x="出生年", y="出生嬰兒數")

```


## 請作表110年台北市、新北市、桃園市、台中市、台南市、高雄市各市依生母生齡出生嬰兒數

```{r}
birth %>% 
  distinct(site_id)
```
```{r}
## substr   substr(x, start, stop)  類似Excel MID函數

substr("桃園市復興區",1,3)

```

```{r}
birth %>% 
  distinct(mother_age)
```

```{r}
birth_110 <- birth %>% 
  filter(statistic_yyy=="110") %>% 
  mutate(city=substr(site_id,1,3)) %>% 
  filter(city %in%  c("臺北市","新北市","桃園市","臺中市","臺南市","高雄市")) %>% 
  mutate(mother_age = factor(mother_age,levels=c("未滿15歲","15～19歲","20～24歲","25～29歲","30～34歲","35～39歲","40～44歲","45～49歲","50歲以上"))) %>% 
  group_by(mother_age,city) %>% 
  summarize(births=sum(birth_count))
  
birth_110
```

```{r}
birth_110 %>% 
  pivot_wider(names_from=city,values_from = births) %>% 
  kable() %>% 
  kable_classic(full_width = F)
```


```{r}
ggplot(birth_110, aes(x=mother_age,y=births)) +
  geom_col() +
  facet_wrap(~city,ncol=3, scales = "free_y") +
  #coord_cartesian()+
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="生母生齡", y="出生嬰兒數")

```
